### ISSUE TITLE
Check this repository

### ISSUE THREAD

**Issue by AkikoAizawa** [Alab-NII/inlinemath#1]
このレポジトリの中身は README とガイドラインだけでしょうか？
もう１つのインライン数式のレポジトリに統合できるようなら統合して、こちらは削除お願いします。

**Comment by iwa2ki** [comment]
こちらは論文にもURIを掲載したレポジトリで，公開なので，統合するわけにはいかないと思います。
inlne-math-detectionの方は非公開のデータも全部入っています

**Comment by AkikoAizawa** [comment]
公開だと気が付きませんでした。失礼しました。
